{
  "kind": "SealedSecret",
  "apiVersion": "bitnami.com/v1alpha1",
  "metadata": {
    "name": "mysql-credentials",
    "namespace": "argocd",
    "creationTimestamp": null
  },
  "spec": {
    "template": {
      "metadata": {
        "name": "mysql-credentials",
        "namespace": "argocd",
        "creationTimestamp": null
      },
      "type": "Opaque"
    },
    "encryptedData": {
      "connection": "AgCwPNo8CToOMbIYr97X2dhl6bbOUx5WNP1x7HofslBPsdkWQFBajaXfd9UxOKmc/61XRxXD2otYnqGGer4IvvddAO6KpsmcJEblvqDraHE/XnDwRXjLg/5VyyFcfQzqe0lenk5IpbUN8Ej5M9Q+4p2mzeIDDwSDXvB+mCPPU6work1fzA+wMmRF2TyJGWOpAIzaxLg5xihv77QZZgGjvqgbAAV+t8zsmRmo+tsXNJCcJGd6RpMyAFcBPrSK0FshwKap8BLyA4b340cMnh+499HXXmWIpCU9YpmDKSj4XsFgmGZDjlme4RW9oOJDftf6KUTtdyq6PD4h3H5d/RZls2AHGGJFuytLqf1XQaNQwnLx4XSkqKV7cU+jqVZhRlBaEri1TNrTYmMcuYGrln1H0Ge0caa94Nxr/hPfmQyouIXazHIBK+OblV+YPq4+MURIJDcxQJr+My3nT9M3xbs6Bw95iykA3mOV/zzM7f2QxxOAYKOouZN/AzNNmy8SgIxxCLcZGvbvag71f44NCXSyMUd44L3ZBEQ0+vwvbn6A6yJRhy3GyS7quW187bRl666tKWClOGPGE5K4Uf7mHiFHj14hV5pauPgxJ1WP0KX9PobAz7pMSgm4stLHbSRSFsx5mPsenRXXuWORyVeekci8TGftpwzC3E3ZwVtfFx9iDkD+ZgIWNxeC4MeIq9F5VoJj6pzeturK4eSJQNbeNsUMVLj/dDh1J0ooBgvCVTT6EGGjBB8=",
      "password": "AgCX9QFdZ07W+HOb6G5YFh1SYYB+aek01E7aQPiduyDwwKDJE619qrb5tkz8ZzGEbVvfhJAD6h17sLfuLIM+DVrCRXqmw6fnPg4mMvpbgj8BbajeJdHkuO6g56ngtJdwCqkz92BzozNfAennoQEqd6mZEe2Dd2Om4yagtoNQRbRtZZq1du+bOKuRp8GRyJEpiBQIlRrMaV4BQX1SmpVgxxQjuEWSYcUSIBsTKv0EWgnv/9OjYbquB1DujMSY4/0PIAcCd7ZnMqto0MbnQUk8GXh2gewaAIXexwarJosKkrAlP3M692RSUajM04M677pYjzoK7u9oLAd1CzowpE7nlgOwoLxfEINll38pmYTLHcZ7jyc7p+i0qouNTPpLJ15Tc+J5Kac9ooUkcZgag8ZixsDoaLqIp2crTjwQPh+mSjpweKCNSFqd2lkWwaR5SPfGimf/g8npO8lhnDoOnBHT/yiPMdkrK8yrSi5wlI9dKlcdmT09zZXO3ojiiJy3ewvtYJF/ff0yX1+8Yn5bxdqQIrqY3GXyuxY4ZLPtG6rOY4FtNymMFvlpI0FDtjOtkNAmSDzR4ywnM8nqN9BUBN1GMT7RaWGjTS6bo+9hNywRmVaYhkZ8Lqzzcqx05dMe0LPrraqVjbb2bd3Sv7qqX5J1MBsNMzTyaIx4LA7G9SuMKyscFxHnfrfR//jnxjX6D/QvdM1wTCAFynS8fM/fI6UU05o=",
      "username": "AgBK9AaeN4jkAjFbsion+G8PKv6eRxukgYHg1SvrVBURgkkmbpE1CDgPAwbgeUC5GlBfox6ADNExCvABk/kBR2chkAdSoCOE7AJJdR6BKxTiNwYzSc+g0EwR/H5oqFfBRTukAdfIHq9VtbTlYe48RPR1fgZVRaq0Lc9hk4ggFXYZkQW0jeiPzs/5tC0bb9Jow+3FdbbTukwXIhlZqCMWAEag4PIHv7tMo0VjJUi9eFuAFvK0GGs0V+6GLEwLgpIdTcoAMtpWO7StuvJlbVspi3ll6jaf6tPGLahXw3ixNcny5OHeLGWL7IzMAFlpKKwYR4P3D5WmKaUrAgqzpE1xd0W62fvCkc0K0P+gUzSToZQ8BHf0Lzzhll4DrTDuzMQnZYzcStkxJvhAjUtzSe2dU039LdN19GY0A5sYI7sgmX4bV3JoIt/dFh4b3VdzrCIbx7ZcvgHkUc3QPfOPxS2EHgAcvAirR3vbFujBTlNbjZBQcm2Cgm8ZGvkXZwV0MvTHEndYXV/CmIRvqVigRsYDnmml36soNRdpzkWRMbFBpLIZ56U8syJM9qA9X6D30oYcsUMFoRHYJyPPDyfQTFDym6re5NQQO7UmriWJfUAGrqnHbsjiT2ueOtGHzN9RwbRW+3zWgXJa7o8shRUw7wPzehyf+hkpLOmoaQiUIsIbYA6CdZgJAZPG8S2lzdBRBPKmIr93mhlAPGqRZnqrGg=="
    }
  }
}
